### ISSUE TITLE
[Bug] Failed to load the PayPal JS SDK script. Error: The script "https://www.paypal.com/sdk/js?client-id= on Safari

### ISSUE THREAD

**Issue by d-tello** [paypal/paypal-js#561]
### Library used
`react-paypal-js` (version `8.1.3`)

### 🐞 Describe the Bug

We are encountering a frequent issue on our website, where the PayPal JS SDK fails to load, especially on certain versions of Safari, most notably in private browsing mode. This results in PayPal buttons not rendering and a significant number of error logs recorded in our Sentry error logging system.

The error message specifically points to a blocked request due to content blockers in Safari, as well as `XMLHttpRequest` access control checks. This issue affects both desktop and mobile Safari versions.

### 🔬 Minimal Reproduction

Navigate to [petsdeli.de](https://www.petsdeli.de/) using **Mobile Safari** or **Safari**.
Enable **private browsing mode**.
Observe the error in the browser's developer console.

### 😕 Actual Behavior

The PayPal JS SDK script fails to load, resulting in the following error in the console:

<img width="755" alt="Screenshot 2024-09-11 at 10 50 10" src="https://github.com/user-attachments/assets/6f0820d4-af45-4118-b875-cc6473a55856">

<img width="761" alt="Screenshot 2024-09-11 at 10 51 09" src="https://github.com/user-attachments/assets/5457d24f-082e-4c79-8d33-9a9ae4498795">

This issue is primarily observed on Safari browsers (both desktop and mobile), particularly in private mode. We see around 1000 error logs per day from our Sentry system related to this problem.

### 🤔 Expected Behavior

The PayPal JS SDK script should load successfully, and the PayPal buttons should render correctly, regardless of whether the user is browsing in private mode or has a content blocker enabled.

### 🌍 Environment

* Node.js: `20.11.0`
* OS: iOS/macOS
* Browser:
    * Mobile Safari 17.5 (60% of occurrences)
    * Mobile Safari 17.6 (13% of occurrences)
    * Safari 17.5 (3%)
    * Mobile Safari 16.6 (1%)
    * Other (20%)

### ➕ Additional Context

* We are using Next.js as the framework for the website.
* Error logging via Sentry shows a significant number of blocked requests, primarily on Safari.

**Comment by waha99922** [comment]
Same error for me. It was working fine couple of days ago.

<img width="461" alt="Screenshot 2024-09-13 at 11 51 39 PM" src="https://github.com/user-attachments/assets/26bb7625-dd78-44a7-a617-4a4907c37c23">

**Comment by ctapang** [comment]
Seeing the same problem on an iOS Reactjs single-page app. Using the Chrome browser does not fix the issue, so the security setting that prevents loading the Paypal module maybe an iOS setting.

**Comment by trailsnail** [comment]
we also see this issue

**Comment by pointblack** [comment]
same here

**Comment by Jaikant** [comment]
Seeing the same issue, could it be because my client id is of a sandbox user?

**Comment by anton-yefanov** [comment]
I have experienced the same bug trying to implement checkout page with `@paypal/react-paypal-js` 
For me the problem was that i was taken clientId from enviroment variables. After i put string directly into initialOptions object the problem was fixed

**Comment by andr3wV** [comment]
> I have experienced the same bug trying to implement checkout page with `@paypal/react-paypal-js` For me the problem was that i was taken clientId from enviroment variables. After i put string directly into initialOptions object the problem was fixed

This doesn't fix it for me. Really sucks b/c I've spent hours trying to figure out these Paypal Buttons and hours more trying to fix this damn bug😭

**Comment by andr3wV** [comment]
Go to your browser's network tab and look for the failed api request. If you click into it, it should tell you a more specific error message. For example mine had the following:

<img width="874" alt="Image" src="https://github.com/user-attachments/assets/206c7ea9-a6da-4718-b627-db669c7ce37a" />

Turns out in production/live mode, you're not supposed to have the buyer-country param!

**Comment by ctapang** [comment]
This issue has not been fixed. There are irrelevant messages above, but the most accurate one is that it is a cross-site scripting issue. Even if the merchant server allows the browser to go ahead and load the javascript file from the Paypal server, the browser still does not execute or does not even load the script.

**Comment by tj-dixon** [comment]
This is still an active issue.
